AUTOIMMUNE = """autoimmune.csv"""
CARDIO = """cardio.csv"""
NEURO = """neuro.csv"""
CANCER = """cancer.csv"""
AGING = """aging.csv"""
ANCESTRY = """ancestry.csv"""
EXPLORATORY = """exploratory.csv"""
PHARMACOGENOMICS = """pharmacogenomics.csv"""
NUTRIGENOMICS = """nutrigenomics.csv"""